### ISSUE TITLE
Customize app.compilerOptions

### ISSUE THREAD

**Issue by nicooprat** [vue-email/compiler#11]
Hi there,

We're using MJML at the moment, in the process to migrate to vue-email. As MJML tags are unknown to Vue (they are processed by MJML after Vue compilation), it warns like this for every tag which makes the logs barely usable:

```
  console.warn
    [Vue warn]: Failed to resolve component: mjml
    If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

We used to ignore those with:

```ts
app.config.compilerOptions.isCustomElement = (tag) => tag === 'mjml' || tag.startsWith('mj-');
```

Would it be possible to access the app or set the config somehow?

Thanks.

PS. Docs for MJML: https://documentation.mjml.io/

**Comment by Flowko** [comment]
please upgrade to `0.8.6`

**Comment by nicooprat** [comment]
I still have the warnings in the console. To be clear: it's ok that those components are not found, I just need the Vue compiler to ignore them and render them as is (since they will be compiled by MJML itself afterwards).

**Comment by Flowko** [comment]
my bad, thought it was related to the other issue, will keep it open

**Comment by Flowko** [comment]
check `0.8.7` 

```ts

const vuemail = config(path, {
    vueCompilerOptions: {
      isCustomElement: tag => tag === 'mjml' || tag.startsWith('mj-'),
    },
  })

```

**Comment by nicooprat** [comment]
Thanks for your quick answer, but I just tried it, with no luck: https://stackblitz.com/edit/stackblitz-starters-feixyn?file=index.ts

<img width="977" alt="image" src="https://github.com/vue-email/compiler/assets/645641/d3e37736-3288-46cd-a089-4896625cc9c8">

```json
"@vue-email/compiler": "^0.8.7"
```

Did I miss something?

**Comment by Flowko** [comment]
weird; ill reopen it, and test it when i have some free time, its one of them issues 😅

**Comment by Flowko** [comment]
so, the code i added should be working, but the issue is on the vue side, not sure why, but there's a lot of issues open related to this, https://github.com/vitejs/vite-plugin-vue/issues/322
will have to wait for a fix that tackles this on the main vue library before closing

**Comment by nicooprat** [comment]
Hi there, sorry to bother, I tried to upgrade to latest `0.8.14` and I'm still having the issue, any news on this one? Thanks :)
